# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-aws-sso" do
  version "1.5.2"

  on_macos do
    on_intel do
      sha256 "e3ecab682d20cf436738ff149dc4bcd446795aac48f11e04381343c58a0877af"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a324eece01031837aeb1db66f13ec049f3a58222601feaec60aea956fac55e04"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1f726b26e29aced1a68d74eef7443ec24b6d04a71e10023f4532d24f752ba3e"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2438b9c853b4841f67d7a8e2b0cdcbefad6a392cc42696c34d46eac7be9d719"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-aws-sso"
  desc "Interactive CLI tool for AWS Single Sign-On (SSO)"
  homepage "https://github.com/theurichde/go-aws-sso"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-aws-sso"

  # No zap stanza required

end
