# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-aws-sso" do
  version "1.5.3"

  on_macos do
    on_arm do
      sha256 "224fb6ec766d67cb10c4312eeafc6ddc6cd1dec7880967978b32c04266000d13"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d74537ec469cc773ec9242548d761a8eca9fa6f750f3efc57be02699b5d42a76"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8dca642381330745a1c7a79329427cef549dc6e8c537194038c7dcce37526313"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "162b7ccb320fcc4daf127cc497245bc786d218c0722b8ae18582d6e294b2c489"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_linux_amd64.tar.gz"
    end
  end

  name "go-aws-sso"
  desc "Interactive CLI tool for AWS Single Sign-On (SSO)"
  homepage "https://github.com/theurichde/go-aws-sso"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-aws-sso"

  # No zap stanza required
end
