# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-aws-sso" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "4fa313f2b111d1674c8a6d401b9e5bb3a93f92b2829f750b0be1ae35a0c024f5"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "32d6a555b5c8d6362322d9ffecc52ade7289aeb85fb888f40de4072a42dd88ac"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ec8924651c101085605dc4b07cdf01b8a85af629bb07b0d7fd9415693a3327c"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e1b7eba6ac76ef4a0836cb5a233580740d9c9ae6dedf609f4f92189e8842006"
      url "https://github.com/theurichde/go-aws-sso/releases/download/v#{version}/go-aws-sso_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-aws-sso"
  desc "Interactive CLI tool for AWS Single Sign-On (SSO)"
  homepage "https://github.com/theurichde/go-aws-sso"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-aws-sso"

  # No zap stanza required

end
