name: Cask Test
on:
  push:
    branches:
      - main
    paths:
      - 'Casks/*.rb'
      - '.github/workflows/tests.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Casks/*.rb'
      - '.github/workflows/tests.yml'
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened

permissions:
  contents: read

env:
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  test-cask:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@848c272c7bfe984a197bd4d16383f4c106ec61e6 # 2026.09.21.1

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Audit cask
        run: brew audit --cask --strict theurichde/go-aws-sso/go-aws-sso

      - name: Verify release artifact
        run: brew fetch --cask --force theurichde/go-aws-sso/go-aws-sso
